# 8a-validation.R
#source(file.path(do, "0a-setup.R"))

library(dplyr)
library(haven)

# --------------------------------------------------
# 1a_import_EWN: data_ewn_update
# --------------------------------------------------

stata <- read_dta(file.path(work2, "data_ewn_update.dta"))
repl <- read_work_data("data_ewn_update")

# 1. Dimensionen
dim(stata)
dim(repl)
names(stata)
names(repl)

# 2. Spaltennamen
setdiff(names(stata), names(repl))
setdiff(names(repl), names(stata))

# 3. Schlüssel prüfen
stata %>%
  count(source, year) %>%
  filter(n > 1)

repl %>%
  count(source, year) %>%
  filter(n > 1)

# 4. Datensätze anhand der Schlüssel vergleichen
comparison <- full_join(
  stata,
  repl,
  by = c("source", "year"),
  suffix = c("_stata", "_r")
)

# 5. Fehlende Schlüssel auf beiden Seiten
anti_join(
  stata, repl,
  by = c("source", "year")
)

anti_join(
  repl, stata,
  by = c("source", "year")
)

# 6. Beispiel: quantitative Abweichung Equity Assets
replication_metrics(
  comparison$aequity_stata,
  comparison$aequity_r
)

# --------------------------------------------------
# IIP portfolio liabilities: Stata vs. R - I
# --------------------------------------------------
# =============================================================================
# Validation of final host-level IIP portfolio liabilities
# =============================================================================
#
# Compare the final host-level IIP liability datasets generated by the
# R replication with the corresponding Stata outputs.
#
# The comparison is conducted separately for equity and debt liabilities
# using host-year as the unique identifier.
# =============================================================================


# -----------------------------------------------------------------------------
# 1. Load R and Stata outputs
# -----------------------------------------------------------------------------

# Equity liabilities
iip_eq_r <- readRDS(
  file.path(work, "IIP_eqliab_host.rds")
)

iip_eq_stata <- haven::read_dta(
  file.path(work2, "IIP_eqliab_host.dta")
)

# Debt liabilities
iip_debt_r <- readRDS(
  file.path(work, "IIP_debtliab_host.rds")
)

iip_debt_stata <- haven::read_dta(
  file.path(work2, "IIP_debtliab_host.dta")
)


# -----------------------------------------------------------------------------
# 2. Check dimensions and uniqueness of host-year identifiers
# -----------------------------------------------------------------------------

cat("\n--- IIP liability validation ---\n")

cat("Equity R dimensions:     ", dim(iip_eq_r), "\n")
cat("Equity Stata dimensions: ", dim(iip_eq_stata), "\n")

cat("Debt R dimensions:       ", dim(iip_debt_r), "\n")
cat("Debt Stata dimensions:   ", dim(iip_debt_stata), "\n")


# Check for duplicate host-year observations

stopifnot(
  !anyDuplicated(iip_eq_r[c("host", "year")]),
  !anyDuplicated(iip_eq_stata[c("host", "year")]),
  !anyDuplicated(iip_debt_r[c("host", "year")]),
  !anyDuplicated(iip_debt_stata[c("host", "year")])
)


# -----------------------------------------------------------------------------
# 3. Merge R and Stata outputs
# -----------------------------------------------------------------------------

iip_eq_comparison <- dplyr::full_join(
  iip_eq_stata,
  iip_eq_r,
  by = c("host", "year"),
  suffix = c("_stata", "_r")
)

iip_debt_comparison <- dplyr::full_join(
  iip_debt_stata,
  iip_debt_r,
  by = c("host", "year"),
  suffix = c("_stata", "_r")
)


# -----------------------------------------------------------------------------
# 4. Check whether both implementations contain the same host-year keys
# -----------------------------------------------------------------------------

eq_only_stata <- dplyr::anti_join(
  iip_eq_stata,
  iip_eq_r,
  by = c("host", "year")
)

eq_only_r <- dplyr::anti_join(
  iip_eq_r,
  iip_eq_stata,
  by = c("host", "year")
)

debt_only_stata <- dplyr::anti_join(
  iip_debt_stata,
  iip_debt_r,
  by = c("host", "year")
)

debt_only_r <- dplyr::anti_join(
  iip_debt_r,
  iip_debt_stata,
  by = c("host", "year")
)

cat("Equity keys only in Stata:", nrow(eq_only_stata), "\n")
cat("Equity keys only in R:    ", nrow(eq_only_r), "\n")
cat("Debt keys only in Stata:  ", nrow(debt_only_stata), "\n")
cat("Debt keys only in R:      ", nrow(debt_only_r), "\n")


# -----------------------------------------------------------------------------
# 5. Numerical validation
# -----------------------------------------------------------------------------

iip_validation <- dplyr::tibble(
  asset_class = c(
    "Equity liabilities",
    "Debt liabilities"
  ),
  
  observations = c(
    nrow(iip_eq_comparison),
    nrow(iip_debt_comparison)
  ),
  
  missing_R = c(
    sum(is.na(iip_eq_comparison$eqliab_IIP_host_r)),
    sum(is.na(iip_debt_comparison$debtliab_IIP_host_r))
  ),
  
  missing_Stata = c(
    sum(is.na(iip_eq_comparison$eqliab_IIP_host_stata)),
    sum(is.na(iip_debt_comparison$debtliab_IIP_host_stata))
  ),
  
  max_abs_difference = c(
    max(
      abs(
        iip_eq_comparison$eqliab_IIP_host_r -
          iip_eq_comparison$eqliab_IIP_host_stata
      ),
      na.rm = TRUE
    ),
    
    max(
      abs(
        iip_debt_comparison$debtliab_IIP_host_r -
          iip_debt_comparison$debtliab_IIP_host_stata
      ),
      na.rm = TRUE
    )
  )
)

print(iip_validation)


# -----------------------------------------------------------------------------
# 6. Validation assertions
# -----------------------------------------------------------------------------

# Both implementations should contain exactly the same host-year observations
stopifnot(
  nrow(eq_only_stata) == 0,
  nrow(eq_only_r) == 0,
  nrow(debt_only_stata) == 0,
  nrow(debt_only_r) == 0
)

# No missing liability values should remain in the final host-level datasets
stopifnot(
  all(iip_validation$missing_R == 0),
  all(iip_validation$missing_Stata == 0)
)

# Numerical differences should be negligible (floating-point precision)
stopifnot(
  all(iip_validation$max_abs_difference < 1e-8)
)

cat(
  "\nFinal host-level IIP liability outputs are numerically equivalent ",
  "across R and Stata up to floating-point precision.\n"
)
